### ISSUE TITLE
sc指令后有“0”会提示sc参数不正确

### ISSUE THREAD

**Issue by KomeijiRan** [Eiriksgata/mirai-rulateday-dice#106]
bug描述：
当使用.sc指令时，诸如 .sc0/1 ， .sc0/1d10 等等，只要指令中有san-0的结果，就会提示“sc指令参数不正确”

bug出现版本：
0.4.5

bug复现：
使用 .sc0/1 ，.sc0/1d10 等等包含san-0的结果的指令

预期结果：
能够正常使用包含san-0结果的sc指令

截屏：

![图片](https://user-images.githubusercontent.com/96311761/187437417-7036550a-a776-4022-8d6d-311417f79229.png)

**Comment by Eiriksgata** [comment]
这个确实是有问题，好像是我当初觉得扣除理智最低应该为1。不过 我看以前好像也没有限制这个，预计下个版本会修复。.
