### ISSUE TITLE
如何给予一个指令骰主权限，例如开关bot骰娘功能

### ISSUE THREAD

**Issue by HaranoShirone** [Eiriksgata/mirai-rulateday-dice#113]
比如.boton|.botoff指令
只允许管理员使用这种可以实现吗？或者说指定骰主，或者一个用户使用。

**Comment by Eiriksgata** [comment]
> 比如.boton|.botoff指令
> 只允许管理员使用这种可以实现吗？或者说指定骰主，或者一个用户使用。

目前还没有这个功能，不过有打算做

**Comment by Eiriksgata** [comment]
如果说从所有指令中 选择其中一个或者几个 给予权限，还是比较难实现的。但是如果说只是 规定 .boton 或者 .botoff 来确认管理员 或者骰主身份则比较容易。

**Comment by HaranoShirone** [comment]
> 

抱歉回复晚了。。只规定.bot on和.bot off来确认管理或骰主身份就足够了，希望能有这个功能，防止群员刷屏乱用2333

**Comment by Eiriksgata** [comment]
> > 
> 
> 抱歉回复晚了。。只规定.bot on和.bot off来确认管理或骰主身份就足够了，希望能有这个功能，防止群员刷屏乱用2333

下个版本会加入这个功能
