### ISSUE TITLE
详细指令介绍页面404了

### ISSUE THREAD

**Issue by zxmacc** [Eiriksgata/mirai-rulateday-dice#128]
大佬，您那个gitee上的详细指令介绍页面404了https://keith404.gitee.io/mirai-rulateday-dice/#/instruction

**Comment by Eiriksgata** [comment]
那个gitee被封了，已经换成 个人域了：https://docs.rulatedaydice.ga/#/instruction

**Comment by zxmacc** [comment]
哦，好的，谢谢大佬

**Comment by KVNVCTW** [comment]
佬，这个网站好像不能用了https://tool.rulatedaydice.ga/#/tools/record，有新网站吗

**Comment by Eiriksgata** [comment]
> 佬，这个网站好像不能用了https://tool.rulatedaydice.ga/#/tools/record，有新网站吗

用https://tool.rulatedaydice.top/#/tools/record

.ga域名被回收了
