### ISSUE TITLE
运行name指令报错

### ISSUE THREAD

**Issue by Messagelcanthelp** [Eiriksgata/mirai-rulateday-dice#130]
不知道为什么，运行name指令报错
. name指令报错

我输入name指令，然后报错了，我同时安装了Console 自动定义回复插件。

我是Windows11AMD系统。
2023-01-18 10:51:37 W/stderr: java.lang.reflect.InvocationTargetException 报错的第一条文本
![capture_20230118110256282](https://user-images.githubusercontent.com/113510493/213072401-e7b58503-513d-4447-91b4-ae37239e2b24.jpg)

**Comment by Eiriksgata** [comment]
因为api坏掉了，这个是调用远程接口的，等春节假期结束我再修复吧

**Comment by Eiriksgata** [comment]
该功能已修复。
