### ISSUE TITLE
加入牌堆功能

### ISSUE THREAD

**Issue by Eiriksgata** [Eiriksgata/mirai-rulateday-dice#52]
形如创建一个牌堆，每人从中抽出后不放回的形式，输出相应的值

**Comment by a08381** [comment]
牌堆功能我觉得也许可以使用Java自带的ECMAScript功能，通过输出牌堆卡片数组，经过拷贝后对拷贝出的新数组进行抽取和删除操作，删空则重新拷贝。感觉会非常易于扩展。同时也许可以提供输出格式，来提供自定义的回复？

**Comment by Eiriksgata** [comment]
> 牌堆功能我觉得也许可以使用Java自带的ECMAScript拓展，通过输出牌堆卡片数组，经过拷贝后对拷贝出的新数组进行抽取和删除操作，删空则重新拷贝。感觉会非常易于拓展。同时也许可以提供输出格式，来提供自定义的回复？

要考虑每个群都独立牌堆的情况，而且也要考虑私聊情况的牌堆使用情况。这边是打算用数据库来做数据存储的功能，数据库本身也提供了随机抽取的功能。
整个牌堆的系统是这样的，牌堆系统分为两部分。一个表作为通用牌堆池，这个池包含了所有的卡牌数据。第二个表是牌种，用于记录不同的卡牌种类，用于导入到通用牌堆池中。

牌种包含例如：塔罗牌系列、扑克、桥牌、麻将、自定义等。

用户需要先在牌种中选择一个，导入到牌堆池中，池中可以包含多种牌种，然后用户在当前的群的牌堆池中随机抽出。
有一点不好的地方在于，用户指令可能会比较多。因为涉及到 添加牌种，清空牌种 等操作。

**Comment by a08381** [comment]
> 
> 牌种包含例如：塔罗牌系列、扑克、桥牌、麻将、自定义等。
> 

哇，所以这个插件以后还可以打麻将吗？

**Comment by Eiriksgata** [comment]
> > 牌种包含例如：塔罗牌系列、扑克、桥牌、麻将、自定义等。
> 
> 哇，所以这个插件以后还可以打麻将吗？

不太会往这方面做，这边只是单纯的做 一个 抽出的行为。 麻将你要玩的话，还不如直接下载一个 麻将游戏，因为麻将游戏本身包含了，很多的规则，例如：碰 杠 吃 等检测，以及胡牌种类检测，这些 都是要细化操作的。

这边仅仅是提供了一个的从池子里抽出的这么一个行为。

**Comment by Eiriksgata** [comment]
该系统分为两个模块：
1. 牌堆：根据所在群号或者用户QQ号构成的一个池（初始没有任何数据），可以通过投放卡组。
2. 卡组：即一个组中，包含了数个数据。可以称为牌种。

**目前实现的指令格式如下：**
1. `.cards`显示存储库中所有的卡组列表。
2. `.cardsadd`创建添加一个牌组。
3. `.drawadd`添加一个卡组至牌堆中。
4. `.draw`从牌堆中不放回的随机取出一个数据（概率平均）。
5. `.draw`显示牌堆中的所有数据。
6. `.drawclear`牌堆清空。

**Comment by Eiriksgata** [comment]
> 该系统分为两个模块：
> 
> 1. 牌堆：根据所在群号或者用户QQ号构成的一个池（初始没有任何数据），可以通过投放卡组。
> 2. 卡组：即一个组中，包含了数个数据。可以称为牌种。
> 
> **目前实现的指令格式如下：**
> 
> 1. `.cards`显示存储库中所有的卡组列表。
> 2. `.cardsadd`创建添加一个牌组。
> 3. `.drawadd`添加一个卡组至牌堆中。
> 4. `.draw`从牌堆中不放回的随机取出一个数据（概率平均）。
> 5. `.drawlist`显示牌堆中的所有数据。
> 6. `.drawclear`牌堆清空。

同样指令也支持驼峰法
 1. `.cards`显示存储库中所有的卡组列表。
 2. `.cardsAdd`创建添加一个牌组。
 3. `.drawAdd`添加一个卡组至牌堆中。
 4. `.draw`从牌堆中不放回的随机取出一个数据（概率平均）。
 5. `.drawList`显示牌堆中的所有数据。
 6. `.drawClear`牌堆清空。

**Comment by Eiriksgata** [comment]
这边默认数据库将会添加若干个牌组数据格式：塔罗牌（分为大阿卡纳与小阿卡纳、扑克牌、麻将

**Comment by Eiriksgata** [comment]
根据实际使用情况，额外再加入两个功能指令（同样支持驼峰法）：
* `.cardsdel`删除卡组，参数为卡组名。
* `.drawhide`隐式抽奖，结果通过私聊回复。
