### ISSUE TITLE
当.coc指令参数数量错误时，会将exception直接作为对话发送

### ISSUE THREAD

**Issue by Pmx990** [Eiriksgata/mirai-rulateday-dice#61]
![图片](https://user-images.githubusercontent.com/29715939/121636148-4fc39b80-ca3c-11eb-9cb1-57d8ab3cec62.png)
如图，应该不需更多描述就能复现。

**Comment by Eiriksgata** [comment]
目前的话，其实很多的指令都没有做详细的 异常情况 文本返回内容，仅是作为exception的摘要描述返回。如果按照正常的人类阅读来说，Number format exception ： for input string 大概意思就是你输入的 这段内容 数值格式不正确，也算作一个提示信息，只不过显然没有中文来的好。因为本身这个项目是按 自定义文本+ 国际化配置形式做的，所以加描述的话，其实还挺麻烦的。不过这边会补齐一些 常见的参数异常 返回中文文本描述提示。
