### ISSUE TITLE
不同用户jrrp命令生成的数字之间相关性很强

### ISSUE THREAD

**Issue by Asterism12** [Eiriksgata/mirai-rulateday-dice#72]
不同用户使用该插件的jrrp命令生成的今日人品值之间有很强的相关性。很容易通过一个人的人品值推知其他人的人品值。

举个例子，比如我今天的人品值是68，小明的人品值是72，小明比我高4；如果明天我使用jrrp得到了自己的人品值是34，那么小明的人品值大概率是38，就算不是，也不会偏离很远。我今天使用jrrp了之后，就能猜到小明的人品值。

这种多个成员之间人品值的强相关性让群成员无法“对比”各自的人品值，因为人品值间的数值差是恒定的或者是变化很小的。希望能去除不同用户人品值间的这种强相关性。

PS：之前使用溯洄系骰娘没有遇到这种问题。

**Comment by Eiriksgata** [comment]
感谢反馈，等我有时间再调整一下算法

**Comment by Eiriksgata** [comment]
`import java.util.Random; `
并不是一个安全的随机数，需要改成
`import java.security.SecureRandom;`

```java
@Override
public String todayRandom(long id, int zone) {
      long timestamp = (System.currentTimeMillis() + (1000L * 60 * 60 * zone)) / (1000 * 60 * 60 * 24);
      int result = new Random(timestamp + id).nextInt(100);
      return CustomText.getText("dice.jrrp.success", result);
}
```
代码 `timestamp + id` 也许也是导致随机数变化不大的原因之一。

**Comment by Eiriksgata** [comment]
代码修复方案：trpg-java-dice 版本改为 1.3.0

**Comment by Eiriksgata** [comment]
解决方案使用Rulateday 插件jar 版本 > 0.4.1
